/*
 * Button_LimitSwitch.h
 *
 *  Created on: Oct 28, 2015
 *      Author: Huan
 */
//#include "include.h"
#ifndef SRC_BUTTON_LIMITSWITCH_BUTTON_LIMITSWITCH_H_
#define SRC_BUTTON_LIMITSWITCH_BUTTON_LIMITSWITCH_H_

#define GPIO_PORT_LIMIT_SW_THROTTLE_DOWN GPIO_PORTA_BASE
#define GPIO_PIN_LIMIT_SW_THROTTLE_DOWN GPIO_PIN_4
#define LIMIT_SW_THROTTLE_DOWN_ON (ROM_GPIOPinRead(GPIO_PORT_LIMIT_SW_THROTTLE_DOWN\
													,GPIO_PIN_LIMIT_SW_THROTTLE_DOWN)\
									& GPIO_PIN_LIMIT_SW_THROTTLE_DOWN)

void Config_Button_LimitSw(void);

#endif /* SRC_BUTTON_LIMITSWITCH_BUTTON_LIMITSWITCH_H_ */
